/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
    "on-surface-variant": "var(--color-on-surface-variant)",
    "surface": "var(--color-surface)",
    "secondary-container": "var(--color-secondary-container)",
    "background": "var(--color-background)",
    "surface-variant": "var(--color-surface-variant)",
    "on-tertiary": "var(--color-on-tertiary)",
    "surface-container-lowest": "var(--color-surface-container-lowest)",
    "primary-fixed": "var(--color-primary-fixed)",
    "surface-dim": "var(--color-surface-dim)",
    "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
    "primary": "var(--color-primary)",
    "tertiary-container": "var(--color-tertiary-container)",
    "surface-container-high": "var(--color-surface-container-high)",
    "outline-variant": "var(--color-outline-variant)",
    "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
    "error": "var(--color-error)",
    "surface-container": "var(--color-surface-container)",
    "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
    "inverse-primary": "var(--color-inverse-primary)",
    "primary-fixed-dim": "var(--color-primary-fixed-dim)",
    "secondary": "var(--color-secondary)",
    "on-background": "var(--color-on-background)",
    "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
    "inverse-surface": "var(--color-inverse-surface)",
    "on-tertiary-container": "var(--color-on-tertiary-container)",
    "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
    "on-surface": "var(--color-on-surface)",
    "on-primary": "var(--color-on-primary)",
    "secondary-fixed": "var(--color-secondary-fixed)",
    "on-primary-fixed": "var(--color-on-primary-fixed)",
    "on-secondary-container": "var(--color-on-secondary-container)",
    "inverse-on-surface": "var(--color-inverse-on-surface)",
    "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
    "on-error": "var(--color-on-error)",
    "on-secondary-fixed": "var(--color-on-secondary-fixed)",
    "tertiary": "var(--color-tertiary)",
    "primary-container": "var(--color-primary-container)",
    "on-error-container": "var(--color-on-error-container)",
    "surface-container-highest": "var(--color-surface-container-highest)",
    "surface-container-low": "var(--color-surface-container-low)",
    "surface-tint": "var(--color-surface-tint)",
    "surface-bright": "var(--color-surface-bright)",
    "on-secondary": "var(--color-on-secondary)",
    "on-primary-container": "var(--color-on-primary-container)",
    "tertiary-fixed": "var(--color-tertiary-fixed)",
    "outline": "var(--color-outline)",
    "error-container": "var(--color-error-container)",
  },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-md": "16px",
          "container-padding-mobile": "20px",
          "unit": "8px",
          "gutter": "24px",
          "container-padding-desktop": "40px",
          "stack-sm": "8px",
          "card-padding": "24px",
          "stack-lg": "32px"
      },
      "fontFamily": {
          "headline-lg": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "display": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
          "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
